### ISSUE TITLE
Version 0.1.5 is not published yet

### ISSUE THREAD

**Issue by margussipria** [ebiznext/sbt-cxf-wsdl2java#14]
Could not found version 0.1.5 but 0.1.4 can be found.

https://oss.sonatype.org/content/groups/public/com/ebiznext/sbt/plugins/sbt-cxf-wsdl2java_2.10_0.13/

**Comment by haakonn** [comment]
Still not published. Documentation should refer to 0.1.4.

**Comment by toggm** [comment]
Waiting for next release as well. When can we expect some progress there?

**Comment by fancywriter** [comment]
Hi guys, do you have any news?

**Comment by fupelaqu** [comment]
version 0.1.5 published

**Comment by Ieva-Zarina** [comment]
Hello! I see that this lib is only released for scala 2.10 (https://oss.sonatype.org/content/groups/public/com/ebiznext/sbt/plugins/sbt-cxf-wsdl2java_2.10_0.13/). Can you release also for 2.11?

**Comment by hayssams** [comment]
@fupelaqu Just bumped up the version to scala 2.11.
Can you publish it on sonatine ?
